ARG BASE_IMAGE
FROM ${BASE_IMAGE:-library/node:15-alpine}

ARG QEMU_ARCH
ENV QEMU_ARCH=${QEMU_ARCH:-x86_64}

COPY .prebuild/qemu/qemu-${QEMU_ARCH}-static /usr/bin/

RUN apk add curl git gcc g++ make python paxctl avahi-compat-libdns_sd avahi-dev dbus

RUN mkdir /node-mdns
WORKDIR /node-mdns

CMD ["./.prebuild/build.sh"]