name: "Prebuild Binaries"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          darwin-x86_64,
        ]
        include:
          - name: darwin-x86_64
            os: macOS-latest

    steps: 
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: macOS - Prebuild Binaries
      run: |
        npm install --ignore-scripts
        node .prebuild/build.js

    - uses: docker-practice/actions-setup-docker@master
    - name: Linux - Prebuild Binaries (Via Docker)
      run: |
        ./build.sh